// -----------------------------------------------
// CATEGORIZE CATEGORY TIER 1
// -----------------------------------------------

type MerchantCategory = {
  subcategory: string;
  confidence: number;
}

/**
 * Common known merchant mappings (high confidence).
 */
export const CATEGORY_MAP: Record<string, MerchantCategory> = {
  // ---------- Groceries ----------
  "whole foods": { subcategory: "groceries", confidence: 0.98 },
  "wholefoods": { subcategory: "groceries", confidence: 0.98 },
  "trader joe's": { subcategory: "groceries", confidence: 0.98 },
  "trader joes": { subcategory: "groceries", confidence: 0.98 },
  "h mart": { subcategory: "groceries", confidence: 0.97 },
  "aldi": { subcategory: "groceries", confidence: 0.97 },
  "lidl": { subcategory: "groceries", confidence: 0.97 },
  "kroger": { subcategory: "groceries", confidence: 0.96 },
  "publix": { subcategory: "groceries", confidence: 0.96 },
  "safeway": { subcategory: "groceries", confidence: 0.96 },
  "wegmans": { subcategory: "groceries", confidence: 0.96 },
  "stop & shop": { subcategory: "groceries", confidence: 0.95 },
  "stop and shop": { subcategory: "groceries", confidence: 0.95 },
  "giant": { subcategory: "groceries", confidence: 0.95 },
  "giant food": { subcategory: "groceries", confidence: 0.95 },
  "meijer": { subcategory: "groceries", confidence: 0.95 },
  "h-e-b": { subcategory: "groceries", confidence: 0.95 },
  "heb": { subcategory: "groceries", confidence: 0.95 },
  "food lion": { subcategory: "groceries", confidence: 0.94 },
  "sprouts": { subcategory: "groceries", confidence: 0.94 },
  "sprouts farmers market": { subcategory: "groceries", confidence: 0.94 },
  "market basket": { subcategory: "groceries", confidence: 0.94 },
  "costco": { subcategory: "groceries", confidence: 0.9 },
  "sam's club": { subcategory: "groceries", confidence: 0.9 },
  "bj's": { subcategory: "groceries", confidence: 0.9 },

  // ---------- Dining Out ----------
  "chipotle": { subcategory: "dining_out", confidence: 0.96 },
  "panera": { subcategory: "dining_out", confidence: 0.95 },
  "sweetgreen": { subcategory: "dining_out", confidence: 0.95 },
  "shake shack": { subcategory: "dining_out", confidence: 0.95 },

  // ---------- Fast Food ----------
  "five guys": { subcategory: "fast_food", confidence: 0.95 },
  "mcdonald's": { subcategory: "fast_food", confidence: 0.97 },
  "mcdonalds": { subcategory: "fast_food", confidence: 0.97 },
  "burger king": { subcategory: "fast_food", confidence: 0.97 },
  "wendy's": { subcategory: "fast_food", confidence: 0.97 },
  "wendys": { subcategory: "fast_food", confidence: 0.97 },
  "taco bell": { subcategory: "fast_food", confidence: 0.97 },
  "kfc": { subcategory: "fast_food", confidence: 0.97 },
  "subway": { subcategory: "fast_food", confidence: 0.95 },

  // ---------- Food Delivery ----------
  "domino's": { subcategory: "food_delivery", confidence: 0.95 },
  "dominos": { subcategory: "food_delivery", confidence: 0.95 },
  "pizza hut": { subcategory: "food_delivery", confidence: 0.95 },
  "doordash": { subcategory: "food_delivery", confidence: 0.96 },
  "uber eats": { subcategory: "food_delivery", confidence: 0.96 },
  "ubereats": { subcategory: "food_delivery", confidence: 0.96 },
  "grubhub": { subcategory: "food_delivery", confidence: 0.96 },
  "seamless": { subcategory: "food_delivery", confidence: 0.96 },
  "postmates": { subcategory: "food_delivery", confidence: 0.95 },

  // ---------- Coffee ----------
  "starbucks": { subcategory: "coffee", confidence: 0.98 },
  "dunkin": { subcategory: "coffee", confidence: 0.98 },
  "dunkin'": { subcategory: "coffee", confidence: 0.98 },
  "peet's": { subcategory: "coffee", confidence: 0.96 },
  "peets": { subcategory: "coffee", confidence: 0.96 },
  "tatte": { subcategory: "coffee", confidence: 0.96 },

  // ---------- Alcohol / Bars ----------
  "total wine": { subcategory: "alcohol", confidence: 0.9 },
  "drizly": { subcategory: "alcohol", confidence: 0.9 },

  // ---------- Rideshare / Transport ----------
  "uber": { subcategory: "rideshare", confidence: 0.96 },
  "lyft": { subcategory: "rideshare", confidence: 0.96 },
  "lime": { subcategory: "transportation", confidence: 0.75 },
  "bird": { subcategory: "transportation", confidence: 0.75 },
  "wanderu": { subcategory: "transportation", confidence: 0.75 },

  // ---------- Fuel ----------
  "shell": { subcategory: "fuel", confidence: 0.9 },
  "exxon": { subcategory: "fuel", confidence: 0.9 },
  "chevron": { subcategory: "fuel", confidence: 0.9 },
  "bp": { subcategory: "fuel", confidence: 0.9 },
  "sunoco": { subcategory: "fuel", confidence: 0.9 },
  "citgo": { subcategory: "fuel", confidence: 0.9 },
  "speedway": { subcategory: "fuel", confidence: 0.9 },

  // ---------- Streaming ----------
  "netflix": { subcategory: "streaming", confidence: 0.98 },
  "hulu": { subcategory: "streaming", confidence: 0.98 },
  "disney plus": { subcategory: "streaming", confidence: 0.98 },
  "disney+": { subcategory: "streaming", confidence: 0.98 },
  "max": { subcategory: "streaming", confidence: 0.7 },
  "hbo max": { subcategory: "streaming", confidence: 0.95 },
  "paramount+": { subcategory: "streaming", confidence: 0.95 },
  "peacock": { subcategory: "streaming", confidence: 0.95 },
  "youtube premium": { subcategory: "streaming", confidence: 0.9 },

  // ---------- Music ----------
  "spotify": { subcategory: "music", confidence: 0.95 },
  "apple music": { subcategory: "music", confidence: 0.95 },
  "pandora": { subcategory: "music", confidence: 0.9 },
  "youtube music": { subcategory: "music", confidence: 0.8 },

  // ---------- Software / Cloud ----------
  "adobe": { subcategory: "software", confidence: 0.9 },
  "github": { subcategory: "software", confidence: 0.85 },
  "openai": { subcategory: "software", confidence: 0.85 },
  "google one": { subcategory: "cloud_services", confidence: 0.9 },
  "icloud": { subcategory: "cloud_services", confidence: 0.9 },
  "dropbox": { subcategory: "cloud_services", confidence: 0.9 },

  // ---------- Shopping ----------
  "amazon": { subcategory: "shopping", confidence: 0.75 },
  "walmart": { subcategory: "shopping", confidence: 0.7 },
  "target": { subcategory: "shopping", confidence: 0.75 },
  "best buy": { subcategory: "electronics", confidence: 0.9 },
  "apple": { subcategory: "electronics", confidence: 0.7 },
  "ikea": { subcategory: "home_goods", confidence: 0.9 },
  "home depot": { subcategory: "home_maintenance", confidence: 0.85 },
  "lowe's": { subcategory: "home_maintenance", confidence: 0.85 },
  "lowes": { subcategory: "home_maintenance", confidence: 0.85 },

  // ---------- Clothing ----------
  "nike": { subcategory: "clothing", confidence: 0.85 },
  "adidas": { subcategory: "clothing", confidence: 0.85 },
  "uniqlo": { subcategory: "clothing", confidence: 0.9 },
  "zara": { subcategory: "clothing", confidence: 0.9 },
  "h&m": { subcategory: "clothing", confidence: 0.9 },
  "hm": { subcategory: "clothing", confidence: 0.85 },
  "lululemon": { subcategory: "clothing", confidence: 0.9 },
  "saks": { subcategory: "clothing", confidence: 0.85 },

  // ---------- Utilities / Internet / Phone ----------
  "comcast": { subcategory: "internet", confidence: 0.9 },
  "xfinity": { subcategory: "internet", confidence: 0.9 },
  "verizon": { subcategory: "phone", confidence: 0.9 },
  "at&t": { subcategory: "phone", confidence: 0.9 },
  "att": { subcategory: "phone", confidence: 0.9 },
  "t-mobile": { subcategory: "phone", confidence: 0.9 },
  "tmobile": { subcategory: "phone", confidence: 0.9 },

  // ---------- Fitness / Wellness ----------
  "planet fitness": { subcategory: "fitness", confidence: 0.95 },
  "la fitness": { subcategory: "fitness", confidence: 0.95 },
  "equinox": { subcategory: "fitness", confidence: 0.9 },

  // ---------- Healthcare / Pharmacy ----------
  "cvs": { subcategory: "pharmacy", confidence: 0.9 },
  "walgreens": { subcategory: "pharmacy", confidence: 0.9 },
  "rite aid": { subcategory: "pharmacy", confidence: 0.9 },

  // ---------- Travel ----------
  "airbnb": { subcategory: "lodging", confidence: 0.95 },
  "marriott": { subcategory: "lodging", confidence: 0.9 },
  "hilton": { subcategory: "lodging", confidence: 0.9 },
  "delta": { subcategory: "flights", confidence: 0.9 },
  "american airlines": { subcategory: "flights", confidence: 0.9 },
  "united": { subcategory: "flights", confidence: 0.85 },
  "southwest": { subcategory: "flights", confidence: 0.9 },

  // ---------- Payments / Transfers ----------
  "venmo": { subcategory: "transfers", confidence: 0.75 },
  "paypal": { subcategory: "transfers", confidence: 0.6 },
  "zelle": { subcategory: "transfers", confidence: 0.75 },
  "cash app": { subcategory: "transfers", confidence: 0.75 },

  // ---------- Fees ----------
  "overdraft fee": { subcategory: "fees", confidence: 0.95 },
  "service fee": { subcategory: "fees", confidence: 0.85 },

  // ---------- Insurance ----------
  "geico": { subcategory: "insurance", confidence: 0.9 },
  "progressive": { subcategory: "insurance", confidence: 0.9 },
  "state farm": { subcategory: "insurance", confidence: 0.9 },

  // ---------- Income ----------
  "payroll": { subcategory: "salary", confidence: 0.75 },
  "direct deposit": { subcategory: "salary", confidence: 0.75 },
};

// -----------------------------------------------
// SUBCATEGORY → CATEGORY MAPPING
// -----------------------------------------------

export const SUBCATEGORY_TO_CATEGORY: Record<string, string> = {
  fast_food: "food",
  dining_out: "food",
  food_delivery: "food",
  groceries: "food",
  bakery: "food",
  coffee: "food",
  alcohol: "food",

  fuel: "transport",
  rideshare: "transport",
  parking: "transport",
  public_transport: "transport",
  car_payment: "transport",
  car_insurance: "transport",
  car_maintenance: "transport",
  transportation: "transport",

  shopping: "shopping",
  clothing: "shopping",
  electronics: "shopping",
  home_goods: "shopping",
  home_maintenance: "shopping",
  personal_care: "shopping",

  streaming: "entertainment",
  music: "entertainment",
  video_games: "entertainment",
  entertainment: "entertainment",
  events: "entertainment",

  software: "subscriptions",
  cloud_services: "subscriptions",
  subscriptions: "subscriptions",

  pharmacy: "health",
  healthcare: "health",
  fitness: "health",

  lodging: "travel",
  flights: "travel",
  travel: "travel",

  salary: "income",
  interest: "income",
  income: "income",

  transfers: "transfers",

  insurance: "bills",
  utilities: "bills",
  rent: "bills",
  mortgage: "bills",
  phone: "bills",
  internet: "bills",
  fees: "bills",
  taxes: "bills",

  education: "education",
  books: "education",

  pets: "pets",

  donations: "giving",
  gifts: "giving",

  misc: "misc",
};

// -----------------------------------------------
// CATEGORIZE CATEGORY TIER 2
// -----------------------------------------------

export type PatternRule = {
  re: RegExp;
  subcategory: string;
  confidence: number;
  note?: string;
};

/**
 * Classification using REGEX
 */
export const CATEGORY_RGX: PatternRule[] = [
  // ---------- Income ----------
  { re: /\b(payroll|direct\s*deposit|salary|paycheck|wages)\b/i, subcategory: "salary", confidence: 0.75 },
  { re: /\b(dividend|interest\s*paid|interest)\b/i, subcategory: "interest", confidence: 0.7 },
  { re: /\b(refund|reversal)\b/i, subcategory: "income", confidence: 0.6 },

  // ---------- Transfers / P2P ----------
  { re: /\b(venmo|zelle|cash\s*app|paypal)\b/i, subcategory: "transfers", confidence: 0.7 },
  { re: /\b(transfer|ach\s*transfer|external\s*transfer|internal\s*transfer)\b/i, subcategory: "transfers", confidence: 0.65 },

  // ---------- Fees ----------
  { re: /\b(overdraft|nsf|returned\s*item|service\s*fee|maintenance\s*fee|late\s*fee)\b/i, subcategory: "fees", confidence: 0.85 },

  // ---------- Taxes ----------
  { re: /\b(irs|tax|revenue\s*service|state\s*tax|property\s*tax)\b/i, subcategory: "taxes", confidence: 0.8 },

  // ---------- Utilities / Internet / Phone ----------
  { re: /\b(electric|electricity|power\s*company|utility)\b/i, subcategory: "utilities", confidence: 0.75 },
  { re: /\b(gas\s*company|natural\s*gas)\b/i, subcategory: "utilities", confidence: 0.75 },
  { re: /\b(water|sewer|trash|waste)\b/i, subcategory: "utilities", confidence: 0.75 },
  { re: /\b(internet|broadband|wifi)\b/i, subcategory: "internet", confidence: 0.75 },
  { re: /\b(cell|mobile|wireless|phone\s*bill)\b/i, subcategory: "phone", confidence: 0.75 },

  // ---------- Housing ----------
  { re: /\b(rent|landlord|leasing)\b/i, subcategory: "rent", confidence: 0.8 },
  { re: /\b(mortgage|escrow)\b/i, subcategory: "mortgage", confidence: 0.8 },
  { re: /\b(home\s*depot|lowe'?s|hardware|lumber|plumbing|paint)\b/i, subcategory: "home_maintenance", confidence: 0.7 },

  // ---------- Groceries ----------
  { re: /\b(grocery|supermarket|market\b|foods?\b|produce|butcher|convenience)\b/i, subcategory: "groceries", confidence: 0.7 },
  { re: /\b(costco|sam'?s\s*club|bj'?s)\b/i, subcategory: "groceries", confidence: 0.6, note: "Warehouse stores also shopping" },

  // ---------- Dining Out / Fast Food / Coffee ----------
  { re: /\b(restaurant|diner|bistro|grill|pizza|taqueria|sushi|ramen|bbq|deli|noodles|house)\b/i, subcategory: "dining_out", confidence: 0.65 },
  { re: /\b(mcdonald|burger\s*king|wendy|taco\s*bell|kfc|subway|halal)\b/i, subcategory: "fast_food", confidence: 0.8 },
  { re: /\b(coffee|cafe|espresso|latte)\b/i, subcategory: "coffee", confidence: 0.75 },
  { re: /\b(bakery)\b/i, subcategory: "bakery", confidence: 0.65 },
  { re: /\b(uber\s*eats|doordash|grubhub|seamless|postmates|deliver(y|ies))\b/i, subcategory: "food_delivery", confidence: 0.85 },

  // ---------- Alcohol ----------
  { re: /\b(liquor|wine|spirits|brewery|taproom|bar\b|pub\b)\b/i, subcategory: "alcohol", confidence: 0.6 },

  // ---------- Transportation ----------
  { re: /\b(uber|lyft|rideshare)\b/i, subcategory: "rideshare", confidence: 0.8 },
  { re: /\b(gas\s*station|fuel|shell|exxon|chevron|bp|sunoco|citgo)\b/i, subcategory: "fuel", confidence: 0.8 },
  { re: /\b(parking|meter|toll|ezpass|e-zpass)\b/i, subcategory: "parking", confidence: 0.75 },
  { re: /\b(mta|mbta|metro|subway|transit|bus|train|amtrak)\b/i, subcategory: "public_transport", confidence: 0.75 },
  { re: /\b(auto\s*payment|car\s*payment)\b/i, subcategory: "car_payment", confidence: 0.75 },
  { re: /\b(auto\s*insurance|car\s*insurance)\b/i, subcategory: "car_insurance", confidence: 0.75 },
  { re: /\b(oil\s*change|tire|tires|mechanic|auto\s*repair|maintenance)\b/i, subcategory: "car_maintenance", confidence: 0.65 },

  // ---------- Shopping / Retail ----------
  { re: /\b(amazon|walmart|target|costco|best\s*buy)\b/i, subcategory: "shopping", confidence: 0.55, note: "Ambiguous retailers" },
  { re: /\b(clothing|apparel|outlet|nike|adidas|uniqlo|zara|h&m|lululemon)\b/i, subcategory: "clothing", confidence: 0.7 },
  { re: /\b(electronic|electronics|computer|laptop|phone\s*store)\b/i, subcategory: "electronics", confidence: 0.6 },
  { re: /\b(furniture|home\s*goods|decor|ikea)\b/i, subcategory: "home_goods", confidence: 0.7 },
  { re: /\b(salon|barber|spa|cosmetic|skincare|sephora|ulta)\b/i, subcategory: "personal_care", confidence: 0.7 },

  // ---------- Subscriptions / Streaming / Software ----------
  { re: /\b(netflix|hulu|disney\+|prime\s*video|hbo|max|peacock|paramount\+)\b/i, subcategory: "streaming", confidence: 0.85 },
  { re: /\b(spotify|apple\s*music|pandora)\b/i, subcategory: "music", confidence: 0.8 },
  { re: /\b(subscription|recurring|membership)\b/i, subcategory: "subscriptions", confidence: 0.65 },
  { re: /\b(adobe|microsoft\s*365|office\s*365|notion|slack|zoom)\b/i, subcategory: "software", confidence: 0.7 },
  { re: /\b(dropbox|google\s*one|icloud|cloud)\b/i, subcategory: "cloud_services", confidence: 0.7 },

  // ---------- Health / Pharmacy / Fitness ----------
  { re: /\b(cvs|walgreens|rite\s*aid|pharmacy)\b/i, subcategory: "pharmacy", confidence: 0.8 },
  { re: /\b(hospital|clinic|doctor|dental|dentist|vision|optometrist)\b/i, subcategory: "healthcare", confidence: 0.7 },
  { re: /\b(gym|fitness|workout|yoga|pilates|planet\s*fitness|equinox)\b/i, subcategory: "fitness", confidence: 0.75 },

  // ---------- Education ----------
  { re: /\b(tuition|university|college|school|course|bootcamp|udemy|coursera|edx)\b/i, subcategory: "education", confidence: 0.7 },
  { re: /\b(textbook|bookstore)\b/i, subcategory: "books", confidence: 0.7 },

  // ---------- Entertainment / Events / Hobbies ----------
  { re: /\b(movie|cinema|theater|ticket|concert|festival|event)\b/i, subcategory: "events", confidence: 0.65 },
  { re: /\b(game|gaming|steam|playstation|xbox|nintendo)\b/i, subcategory: "video_games", confidence: 0.75 },
  { re: /\b(entertainment|arcade)\b/i, subcategory: "entertainment", confidence: 0.6 },

  // ---------- Travel ----------
  { re: /\b(airbnb|hotel|inn|resort|marriott|hilton|hyatt)\b/i, subcategory: "lodging", confidence: 0.75 },
  { re: /\b(airlines?|flight|delta|united|american\s*airlines|southwest|jetblue)\b/i, subcategory: "flights", confidence: 0.7 },
  { re: /\b(uber\s*rental|rental\s*car|hertz|avis|enterprise)\b/i, subcategory: "travel", confidence: 0.6 },

  // ---------- Insurance ----------
  { re: /\b(insurance|geico|progressive|state\s*farm|allstate)\b/i, subcategory: "insurance", confidence: 0.75 },

  // ---------- Pets ----------
  { re: /\b(vet|veterinary|pet\s*store|petco|petsmart)\b/i, subcategory: "pets", confidence: 0.75 },

  // ---------- Donations / Gifts ----------
  { re: /\b(donation|charity|nonprofit)\b/i, subcategory: "donations", confidence: 0.75 },
  { re: /\b(gift|giftcard|gift\s*card)\b/i, subcategory: "gifts", confidence: 0.6 },
];

// -----------------------------------------------
// MERCHANT MAPPINGS
// -----------------------------------------------
export const MERCHANT_NAME_MAP: Record<string, string> = {

  // -----------------------------------------------
  // GROCERY STORES
  // -----------------------------------------------
  "whole foods": "Whole Foods",
  "wholefds": "Whole Foods",
  "wholefds ink": "Whole Foods",
  "wholefds rvr": "Whole Foods",
  "trader joe s": "Trader Joe's",
  "trader joes": "Trader Joe's",
  "trader joe's": "Trader Joe's",
  "h mart": "H Mart",
  "hmart": "H Mart",
  "aldi": "Aldi",
  "lidl": "Lidl",
  "kroger": "Kroger",
  "publix": "Publix",
  "safeway": "Safeway",
  "wegmans": "Wegmans",
  "stop & shop": "Stop & Shop",
  "stop and shop": "Stop & Shop",
  "giant food": "Giant Food",
  "giant": "Giant",
  "meijer": "Meijer",
  "h-e-b": "H-E-B",
  "heb": "H-E-B",
  "food lion": "Food Lion",
  "sprouts": "Sprouts",
  "market basket": "Market Basket",
  "costco whse": "Costco",
  "costco": "Costco",
  "sam's club": "Sam's Club",
  "sams club": "Sam's Club",
  "bj's": "BJ's",
  "bjs wholesale": "BJ's",
  "harris teeter": "Harris Teeter",
  "shoprite": "ShopRite",
  "shop rite": "ShopRite",
  "acme markets": "ACME Markets",
  "acme": "ACME Markets",
  "weis markets": "Weis Markets",
  "weis": "Weis Markets",
  "fresh market": "The Fresh Market",
  "the fresh market": "The Fresh Market",
  "earth fare": "Earth Fare",
  "natural grocers": "Natural Grocers",
  "lucky supermarkets": "Lucky Supermarkets",
  "stater bros": "Stater Bros.",
  "vons": "Vons",
  "pavilions": "Pavilions",
  "ralphs": "Ralphs",
  "fry's food": "Fry's Food",
  "frys food": "Fry's Food",
  "king soopers": "King Soopers",
  "smith's food": "Smith's Food",
  "dillons": "Dillons",
  "pick n save": "Pick 'n Save",
  "copps": "Copps",
  "metro market": "Metro Market",
  "mariano's": "Mariano's",
  "marianos": "Mariano's",
  "jewel osco": "Jewel-Osco",
  "jewel-osco": "Jewel-Osco",
  "jewel": "Jewel-Osco",
  "dominick's": "Dominick's",
  "dominicks": "Dominick's",
  "schnucks": "Schnucks",
  "dierbergs": "Dierbergs",
  "hy-vee": "Hy-Vee",
  "hyvee": "Hy-Vee",
  "fareway": "Fareway",
  "price chopper": "Price Chopper",
  "hannaford": "Hannaford",
  "shaw's": "Shaw's",
  "shaws": "Shaw's",
  "star market": "Star Market",
  "big y": "Big Y",
  "brookshire": "Brookshire's",
  "brookshires": "Brookshire's",
  "united supermarkets": "United Supermarkets",
  "winco": "WinCo Foods",
  "winco foods": "WinCo Foods",
  "grocery outlet": "Grocery Outlet",
  "piggly wiggly": "Piggly Wiggly",
  "ingles": "Ingles Markets",
  "ingles markets": "Ingles Markets",
  "winn dixie": "Winn-Dixie",
  "winn-dixie": "Winn-Dixie",
  "bi-lo": "BI-LO",
  "bilo": "BI-LO",
  "save a lot": "Save A Lot",
  "food 4 less": "Food 4 Less",
  "food4less": "Food 4 Less",
  "smart & final": "Smart & Final",
  "smart and final": "Smart & Final",
  "99 ranch": "99 Ranch Market",
  "99 ranch market": "99 Ranch Market",
  "mitsuwa": "Mitsuwa Marketplace",
  "mitsuwa marketplace": "Mitsuwa Marketplace",
  "marukai": "Marukai",
  "zupan's": "Zupan's Markets",
  "new seasons": "New Seasons Market",
  "central market": "Central Market",
  "niemann foods": "Niemann Foods",
  "town fair tire": "Town Fair Tire",
  "neighborhood convenience": "Neighborhood Convenience",
  "college convenience": "College Convenience",
  "sam halal food": "Sam Halal Food",
  "azzab halal food": "Azzab Halal Food",

  // -----------------------------------------------
  // FAST FOOD
  // -----------------------------------------------
  "mcdonald's": "McDonald's",
  "mcdonalds": "McDonald's",
  "burger king": "Burger King",
  "wendy's": "Wendy's",
  "wendys": "Wendy's",
  "taco bell": "Taco Bell",
  "kfc": "KFC",
  "chick-fil-a": "Chick-fil-A",
  "chick fil a": "Chick-fil-A",
  "chickfila": "Chick-fil-A",
  "popeyes": "Popeyes",
  "popeye's": "Popeyes",
  "sonic": "Sonic",
  "sonic drive": "Sonic",
  "sonic drivein": "Sonic",
  "dairy queen": "Dairy Queen",
  "dq grill": "Dairy Queen",
  "five guys": "Five Guys",
  "in-n-out": "In-N-Out Burger",
  "in n out": "In-N-Out Burger",
  "whataburger": "Whataburger",
  "jack in the box": "Jack in the Box",
  "jack in box": "Jack in the Box",
  "carl's jr": "Carl's Jr.",
  "carls jr": "Carl's Jr.",
  "hardee's": "Hardee's",
  "hardees": "Hardee's",
  "arby's": "Arby's",
  "arbys": "Arby's",
  "culver's": "Culver's",
  "culvers": "Culver's",
  "steak 'n shake": "Steak 'n Shake",
  "steak n shake": "Steak 'n Shake",
  "steakn shake": "Steak 'n Shake",
  "white castle": "White Castle",
  "cook out": "Cook Out",
  "cookout": "Cook Out",
  "del taco": "Del Taco",
  "checkers": "Checkers",
  "rally's": "Rally's",
  "rallys": "Rally's",
  "wingstop": "Wingstop",
  "wing stop": "Wingstop",
  "raising cane": "Raising Cane's",
  "raising canes": "Raising Cane's",
  "zaxby's": "Zaxby's",
  "zaxbys": "Zaxby's",
  "bojangles": "Bojangles",
  "bojangle's": "Bojangles",
  "captain d's": "Captain D's",
  "captain ds": "Captain D's",
  "long john silver": "Long John Silver's",
  "church's chicken": "Church's Chicken",
  "churchs chicken": "Church's Chicken",
  "el pollo loco": "El Pollo Loco",
  "fatburger": "Fatburger",
  "smashburger": "Smashburger",
  "shake shack": "Shake Shack",
  "habit burger": "The Habit Burger",
  "habit restaur": "The Habit Burger",
  "freddy's": "Freddy's",
  "freddys": "Freddy's",
  "steak escape": "Steak Escape",
  "krystal": "Krystal",
  "little caesars": "Little Caesars",
  "little caesar": "Little Caesars",
  "papa john's": "Papa John's",
  "papa johns": "Papa John's",
  "papa murphy": "Papa Murphy's",
  "round table pizza": "Round Table Pizza",
  "cicis pizza": "Cicis Pizza",
  "godfather's pizza": "Godfather's Pizza",
  "jets pizza": "Jet's Pizza",
  "hungry howie": "Hungry Howie's",
  "marco's pizza": "Marco's Pizza",
  "marcos pizza": "Marco's Pizza",

  // -----------------------------------------------
  // DINING OUT / RESTAURANTS
  // -----------------------------------------------
  "chipotle": "Chipotle",
  "panera": "Panera Bread",
  "panera bread": "Panera Bread",
  "sweetgreen": "Sweetgreen",
  "olive garden": "Olive Garden",
  "applebee's": "Applebee's",
  "applebees": "Applebee's",
  "chili's": "Chili's",
  "chilis": "Chili's",
  "outback steakhouse": "Outback Steakhouse",
  "outback": "Outback Steakhouse",
  "texas roadhouse": "Texas Roadhouse",
  "longhorn steakhouse": "LongHorn Steakhouse",
  "longhorn": "LongHorn Steakhouse",
  "red lobster": "Red Lobster",
  "red robin": "Red Robin",
  "ihop": "IHOP",
  "denny's": "Denny's",
  "dennys": "Denny's",
  "waffle house": "Waffle House",
  "cracker barrel": "Cracker Barrel",
  "bob evans": "Bob Evans",
  "perkins": "Perkins",
  "friendly's": "Friendly's",
  "friendlys": "Friendly's",
  "sizzler": "Sizzler",
  "golden corral": "Golden Corral",
  "the cheesecake factory": "The Cheesecake Factory",
  "cheesecake factory": "The Cheesecake Factory",
  "bj's restaurant": "BJ's Restaurant",
  "bj's brewhouse": "BJ's Restaurant",
  "buffalo wild wings": "Buffalo Wild Wings",
  "bdubs": "Buffalo Wild Wings",
  "hooters": "Hooters",
  "p.f. chang": "P.F. Chang's",
  "pf chang": "P.F. Chang's",
  "benihana": "Benihana",
  "ruth's chris": "Ruth's Chris Steak House",
  "ruths chris": "Ruth's Chris Steak House",
  "morton's": "Morton's The Steakhouse",
  "mortons steakhouse": "Morton's The Steakhouse",
  "flemings": "Fleming's Prime Steakhouse",
  "fleming's": "Fleming's Prime Steakhouse",
  "capital grille": "The Capital Grille",
  "the capital grille": "The Capital Grille",
  "yardhouse": "Yard House",
  "yard house": "Yard House",
  "seasons 52": "Seasons 52",
  "bonefish grill": "Bonefish Grill",
  "bahama breeze": "Bahama Breeze",
  "cheddar's": "Cheddar's Scratch Kitchen",
  "cheddars": "Cheddar's Scratch Kitchen",
  "noodles & company": "Noodles & Company",
  "noodles and company": "Noodles & Company",
  "noodles company": "Noodles & Company",
  "moe's southwest": "Moe's Southwest Grill",
  "moes southwest": "Moe's Southwest Grill",
  "qdoba": "Qdoba",
  "firehouse subs": "Firehouse Subs",
  "jersey mike": "Jersey Mike's Subs",
  "jersey mikes": "Jersey Mike's Subs",
  "jimmy john": "Jimmy John's",
  "jimmy johns": "Jimmy John's",
  "jason's deli": "Jason's Deli",
  "jasons deli": "Jason's Deli",
  "mcalister's deli": "McAlister's Deli",
  "mcalisters deli": "McAlister's Deli",
  "corner bakery": "Corner Bakery Cafe",
  "boston market": "Boston Market",
  "panda express": "Panda Express",
  "pei wei": "Pei Wei",
  "genghis grill": "Genghis Grill",
  "bd's mongolian": "BD's Mongolian Grill",
  "hot topic": "Hot Topic",
  "jongro bbq": "Jongro BBQ",
  "bonchon": "Bonchon",
  "happy lamb": "Happy Lamb Hot Pot",
  "gyu-kaku": "Gyu-Kaku",
  "gyu kaku": "Gyu-Kaku",
  "spring shabu": "Spring Shabu-Shabu",
  "bcd tofu": "BCD Tofu House",
  "canteen deli": "Canteen Deli & Cafe",
  "new noodle village": "New Noodle Village",
  "la gran uruguaya": "La Gran Uruguaya",

  // -----------------------------------------------
  // COFFEE & CAFES
  // -----------------------------------------------
  "starbucks": "Starbucks",
  "dunkin": "Dunkin'",
  "dunkin'": "Dunkin'",
  "dunkin donuts": "Dunkin'",
  "peet's": "Peet's Coffee",
  "peets": "Peet's Coffee",
  "peet's coffee": "Peet's Coffee",
  "tatte": "Tatte Bakery",
  "tatte bakery": "Tatte Bakery",
  "tim hortons": "Tim Hortons",
  "caribou coffee": "Caribou Coffee",
  "caribou": "Caribou Coffee",
  "dutch bros": "Dutch Bros Coffee",
  "dutch brothers": "Dutch Bros Coffee",
  "coffee bean": "The Coffee Bean & Tea Leaf",
  "coffee bean tea": "The Coffee Bean & Tea Leaf",
  "scooter's coffee": "Scooter's Coffee",
  "scooters coffee": "Scooter's Coffee",
  "biggby": "Biggby Coffee",
  "biggby coffee": "Biggby Coffee",
  "einstein bros": "Einstein Bros. Bagels",
  "einstein bagels": "Einstein Bros. Bagels",
  "bruegger's": "Bruegger's Bagels",
  "brueggers": "Bruegger's Bagels",
  "noah's bagels": "Noah's Bagels",
  "noahs bagels": "Noah's Bagels",
  "la madeleine": "La Madeleine",

  // -----------------------------------------------
  // FOOD DELIVERY
  // -----------------------------------------------
  "doordash": "DoorDash",
  "door dash": "DoorDash",
  "dd *doordash": "DoorDash",
  "uber eats": "Uber Eats",
  "ubereats": "Uber Eats",
  "grubhub": "GrubHub",
  "grub hub": "GrubHub",
  "seamless": "Seamless",
  "postmates": "Postmates",
  "caviar": "Caviar",
  "instacart": "Instacart",
  "shipt": "Shipt",
  "gopuff": "GoPuff",
  "go puff": "GoPuff",
  "domino's": "Domino's",
  "dominos": "Domino's",
  "pizza hut": "Pizza Hut",

  // -----------------------------------------------
  // RIDESHARE & TRANSPORT
  // -----------------------------------------------
  "lyft": "Lyft",
  "uber": "Uber",
  "waymo": "Waymo",
  "via transport": "Via",
  "bird scooter": "Bird",
  "bird": "Bird",
  "lime": "Lime",
  "spin scooter": "Spin",
  "razor scooter": "Razor",
  "wanderu": "Wanderu",
  "greyhound": "Greyhound",
  "megabus": "Megabus",
  "flixbus": "FlixBus",
  "amtrak": "Amtrak",
  "nyct paygo": "NYC MTA",
  "mta*nyct": "NYC MTA",
  "mbta": "MBTA",
  "wmata": "WMATA",
  "bay area rapid": "BART",
  "bart": "BART",
  "chicago transit": "CTA",
  "cta ventra": "CTA",
  "septa": "SEPTA",
  "metro transit": "Metro Transit",
  "trimet": "TriMet",
  "sound transit": "Sound Transit",
  "pspt boston2 prk": "Parking",
  "parkwhiz": "ParkWhiz",
  "spothero": "SpotHero",
  "parkmobile": "ParkMobile",
  "passport parking": "Passport Parking",
  "paybyphone": "PayByPhone",
  "ezpass": "E-ZPass",
  "e-zpass": "E-ZPass",
  "sunpass": "SunPass",
  "peach pass": "Peach Pass",
  "fastrak": "FasTrak",
  "pikepass": "PikePass",

  // -----------------------------------------------
  // FUEL
  // -----------------------------------------------
  "speedway": "Speedway",
  "shell": "Shell",
  "exxon": "ExxonMobil",
  "exxonmobil": "ExxonMobil",
  "mobil": "ExxonMobil",
  "chevron": "Chevron",
  "bp": "BP",
  "sunoco": "Sunoco",
  "citgo": "Citgo",
  "marathon": "Marathon",
  "marathon petroleum": "Marathon",
  "casey's": "Casey's General Store",
  "caseys": "Casey's General Store",
  "pilot flying j": "Pilot Flying J",
  "pilot travel": "Pilot Flying J",
  "flying j": "Pilot Flying J",
  "love's travel": "Love's Travel Stops",
  "loves travel": "Love's Travel Stops",
  "ta travel": "TravelCenters of America",
  "travel centers": "TravelCenters of America",
  "kwik trip": "Kwik Trip",
  "kwiktrip": "Kwik Trip",
  "wawa": "Wawa",
  "sheetz": "Sheetz",
  "racetrac": "RaceTrac",
  "race trac": "RaceTrac",
  "circle k": "Circle K",
  "7-eleven": "7-Eleven",
  "7 eleven": "7-Eleven",
  "sevenelevn": "7-Eleven",
  "quiktrip": "QuikTrip",
  "quick trip": "QuikTrip",
  "holiday station": "Holiday Station Stores",
  "holiday stationstores": "Holiday Station Stores",
  "thorntons": "Thorntons",
  "turkey hill": "Turkey Hill",
  "cumberland farms": "Cumberland Farms",
  "cumby's": "Cumberland Farms",
  "cumbys": "Cumberland Farms",
  "gate petroleum": "Gate Petroleum",
  "road ranger": "Road Ranger",
  "maverik": "Maverik",
  "sinclair": "Sinclair Oil",
  "texaco": "Texaco",
  "valero": "Valero",
  "phillips 66": "Phillips 66",
  "76 gas": "76",
  "conoco": "Conoco",

  // -----------------------------------------------
  // SHOPPING / RETAIL
  // -----------------------------------------------
  "amazon mktpl": "Amazon",
  "amazon reta": "Amazon",
  "amazon": "Amazon",
  "amzn": "Amazon",
  "walmart": "Walmart",
  "wal-mart": "Walmart",
  "target": "Target",
  "home depot": "Home Depot",
  "lowe's": "Lowe's",
  "lowes": "Lowe's",
  "ikea": "IKEA",
  "bed bath": "Bed Bath & Beyond",
  "bed bath & beyond": "Bed Bath & Beyond",
  "williams sonoma": "Williams Sonoma",
  "williams-sonoma": "Williams Sonoma",
  "pottery barn": "Pottery Barn",
  "west elm": "West Elm",
  "crate and barrel": "Crate & Barrel",
  "crate & barrel": "Crate & Barrel",
  "restoration hardware": "RH",
  "pier 1": "Pier 1 Imports",
  "world market": "Cost Plus World Market",
  "tuesday morning": "Tuesday Morning",
  "tj maxx": "TJ Maxx",
  "tjmaxx": "TJ Maxx",
  "t.j. maxx": "TJ Maxx",
  "marshalls": "Marshalls",
  "ross dress": "Ross Dress for Less",
  "ross stores": "Ross Dress for Less",
  "burlington coat": "Burlington",
  "burlington": "Burlington",
  "nordstrom rack": "Nordstrom Rack",
  "nordstrom": "Nordstrom",
  "saks fifth": "Saks Fifth Avenue",
  "saks": "Saks Fifth Avenue",
  "neiman marcus": "Neiman Marcus",
  "bloomingdale's": "Bloomingdale's",
  "bloomingdales": "Bloomingdale's",
  "macy's": "Macy's",
  "macys": "Macy's",
  "jcpenney": "JCPenney",
  "j.c. penney": "JCPenney",
  "kohl's": "Kohl's",
  "kohls": "Kohl's",
  "dillard's": "Dillard's",
  "dillards": "Dillard's",
  "belk": "Belk",
  "dollar tree": "Dollar Tree",
  "dollar general": "Dollar General",
  "family dollar": "Family Dollar",
  "five below": "Five Below",
  "big lots": "Big Lots",
  "ollie's bargain": "Ollie's Bargain Outlet",
  "ollies bargain": "Ollie's Bargain Outlet",
  "harbor freight": "Harbor Freight Tools",
  "menards": "Menards",
  "ace hardware": "Ace Hardware",
  "true value": "True Value",
  "tractor supply": "Tractor Supply Co.",
  "northern tool": "Northern Tool",
  "overstock": "Overstock",
  "wayfair": "Wayfair",
  "etsy": "Etsy",
  "ebay": "eBay",

  // -----------------------------------------------
  // CLOTHING & APPAREL
  // -----------------------------------------------
  "nike": "Nike",
  "adidas": "Adidas",
  "under armour": "Under Armour",
  "lululemon": "Lululemon",
  "lululemoncom": "Lululemon",
  "gap": "Gap",
  "old navy": "Old Navy",
  "banana republic": "Banana Republic",
  "j.crew": "J.Crew",
  "jcrew": "J.Crew",
  "j crew": "J.Crew",
  "ann taylor": "Ann Taylor",
  "loft": "LOFT",
  "ann taylor loft": "LOFT",
  "express": "Express",
  "forever 21": "Forever 21",
  "forever21": "Forever 21",
  "h&m": "H&M",
  "h & m": "H&M",
  "hm": "H&M",
  "zara": "Zara",
  "uniqlo": "Uniqlo",
  "aeropostale": "Aeropostale",
  "hollister": "Hollister",
  "abercrombie": "Abercrombie & Fitch",
  "american eagle": "American Eagle",
  "ae outfitters": "American Eagle",
  "victoria's secret": "Victoria's Secret",
  "victorias secret": "Victoria's Secret",
  "pink victoria": "Victoria's Secret PINK",
  "bath body works": "Bath & Body Works",
  "bath & body": "Bath & Body Works",
  "patagonia": "Patagonia",
  "the north face": "The North Face",
  "north face": "The North Face",
  "columbia sportswear": "Columbia Sportswear",
  "columbia": "Columbia Sportswear",
  "rei": "REI",
  "rei co-op": "REI",
  "dick's sporting": "Dick's Sporting Goods",
  "dicks sporting": "Dick's Sporting Goods",
  "academy sports": "Academy Sports",
  "hibbett sports": "Hibbett Sports",
  "foot locker": "Foot Locker",
  "footlocker": "Foot Locker",
  "finish line": "Finish Line",
  "jd sports": "JD Sports",
  "skechers": "Skechers",
  "dsw": "DSW",
  "shoe carnival": "Shoe Carnival",
  "payless": "Payless ShoeSource",
  "steve madden": "Steve Madden",
  "nine west": "Nine West",
  "ralph lauren": "Ralph Lauren",
  "polo ralph lauren": "Ralph Lauren",
  "tommy hilfiger": "Tommy Hilfiger",
  "calvin klein": "Calvin Klein",
  "michael kors": "Michael Kors",
  "coach": "Coach",
  "kate spade": "Kate Spade",
  "tory burch": "Tory Burch",

  // -----------------------------------------------
  // ELECTRONICS
  // -----------------------------------------------
  "apple.com/bill": "Apple",
  "apple.com": "Apple",
  "apple store": "Apple",
  "apple": "Apple",
  "best buy": "Best Buy",
  "micro center": "Micro Center",
  "microcenter": "Micro Center",
  "fry's electronics": "Fry's Electronics",
  "frys electronics": "Fry's Electronics",
  "b&h photo": "B&H Photo",
  "b and h photo": "B&H Photo",
  "adorama": "Adorama",
  "newegg": "Newegg",

  // -----------------------------------------------
  // PERSONAL CARE & BEAUTY
  // -----------------------------------------------
  "sephora": "Sephora",
  "ulta": "Ulta Beauty",
  "ulta beauty": "Ulta Beauty",
  "cvs": "CVS",
  "cvs pharmacy": "CVS",
  "walgreens": "Walgreens",
  "rite aid": "Rite Aid",
  "sally beauty": "Sally Beauty",
  "great clips": "Great Clips",
  "supercuts": "Supercuts",
  "sport clips": "Sport Clips",
  "floyd's barbershop": "Floyd's Barbershop",
  "floyds barbershop": "Floyd's Barbershop",
  "regis salon": "Regis Salon",
  "fantastic sam": "Fantastic Sam's",
  "fantastic sams": "Fantastic Sam's",
  "massage envy": "Massage Envy",
  "hand and stone": "Hand & Stone Massage",
  "european wax": "European Wax Center",
  "drybar": "Drybar",

  // -----------------------------------------------
  // HEALTH & FITNESS
  // -----------------------------------------------
  "planet fitness": "Planet Fitness",
  "la fitness": "LA Fitness",
  "equinox": "Equinox",
  "crunch fitness": "Crunch Fitness",
  "crunch gym": "Crunch Fitness",
  "24 hour fitness": "24 Hour Fitness",
  "24hr fitness": "24 Hour Fitness",
  "anytime fitness": "Anytime Fitness",
  "gold's gym": "Gold's Gym",
  "golds gym": "Gold's Gym",
  "ymca": "YMCA",
  "crossfit": "CrossFit",
  "orangetheory": "Orangetheory Fitness",
  "orange theory": "Orangetheory Fitness",
  "f45": "F45 Training",
  "soul cycle": "SoulCycle",
  "soulcycle": "SoulCycle",
  "solidcore": "[solidcore]",
  "barry's bootcamp": "Barry's Bootcamp",
  "barrys bootcamp": "Barry's Bootcamp",
  "pure barre": "Pure Barre",
  "club pilates": "Club Pilates",
  "corepower yoga": "CorePower Yoga",
  "lifetime fitness": "Life Time Fitness",
  "lifetime athletic": "Life Time Fitness",
  "blink fitness": "Blink Fitness",
  "snap fitness": "Snap Fitness",

  // -----------------------------------------------
  // STREAMING & ENTERTAINMENT
  // -----------------------------------------------
  "netflix": "Netflix",
  "hulu": "Hulu",
  "disney+": "Disney+",
  "disney plus": "Disney+",
  "disneyplus": "Disney+",
  "hbo max": "Max",
  "max streaming": "Max",
  "hbomax": "Max",
  "paramount+": "Paramount+",
  "paramount plus": "Paramount+",
  "peacock": "Peacock",
  "apple tv": "Apple TV+",
  "apple tv+": "Apple TV+",
  "amazon prime video": "Prime Video",
  "prime video": "Prime Video",
  "discovery+": "Discovery+",
  "discovery plus": "Discovery+",
  "espn+": "ESPN+",
  "espn plus": "ESPN+",
  "fubo": "FuboTV",
  "fubotv": "FuboTV",
  "sling tv": "Sling TV",
  "slingtv": "Sling TV",
  "youtube tv": "YouTube TV",
  "youtubetv": "YouTube TV",
  "philo": "Philo",
  "directv stream": "DirecTV Stream",
  "directv": "DirecTV",
  "showtime": "Showtime",
  "starz": "Starz",
  "mubi": "MUBI",
  "criterion channel": "The Criterion Channel",
  "shudder": "Shudder",
  "amc networks": "AMC+",
  "amc+": "AMC+",
  "fandango": "Fandango",
  "atom tickets": "Atom Tickets",
  "regal cinemas": "Regal Cinemas",
  "amc theaters": "AMC Theatres",
  "amc theatre": "AMC Theatres",
  "cinemark": "Cinemark",
  "alamo drafthouse": "Alamo Drafthouse",

  // -----------------------------------------------
  // MUSIC
  // -----------------------------------------------
  "spotify": "Spotify",
  "apple music": "Apple Music",
  "pandora": "Pandora",
  "youtube music": "YouTube Music",
  "tidal": "Tidal",
  "amazon music": "Amazon Music",
  "deezer": "Deezer",
  "soundcloud": "SoundCloud",
  "bandcamp": "Bandcamp",
  "ticketmaster": "Ticketmaster",
  "livenation": "Live Nation",
  "live nation": "Live Nation",
  "stubhub": "StubHub",
  "seatgeek": "SeatGeek",
  "vivid seats": "Vivid Seats",

  // -----------------------------------------------
  // GAMING
  // -----------------------------------------------
  "steam": "Steam",
  "playstation": "PlayStation",
  "psn": "PlayStation Network",
  "xbox": "Xbox",
  "xbox live": "Xbox",
  "nintendo": "Nintendo",
  "nintendo eshop": "Nintendo",
  "epic games": "Epic Games",
  "battle.net": "Battle.net",
  "battlenet": "Battle.net",
  "ea games": "EA",
  "origin": "EA Origin",
  "ubisoft": "Ubisoft",
  "twitch": "Twitch",
  "gamestop": "GameStop",

  // -----------------------------------------------
  // SOFTWARE & CLOUD
  // -----------------------------------------------
  "openai": "OpenAI",
  "openai chatgpt": "OpenAI",
  "chatgpt": "OpenAI",
  "adobe": "Adobe",
  "adobe creative": "Adobe",
  "microsoft": "Microsoft",
  "microsoft 365": "Microsoft 365",
  "office 365": "Microsoft 365",
  "google one": "Google One",
  "google storage": "Google One",
  "icloud": "iCloud",
  "dropbox": "Dropbox",
  "box.com": "Box",
  "github": "GitHub",
  "notion": "Notion",
  "slack": "Slack",
  "zoom": "Zoom",
  "docusign": "DocuSign",
  "squarespace": "Squarespace",
  "wix": "Wix",
  "godaddy": "GoDaddy",
  "namecheap": "Namecheap",
  "aws": "Amazon Web Services",
  "amazon web services": "Amazon Web Services",
  "google cloud": "Google Cloud",
  "digitalocean": "DigitalOcean",
  "cloudflare": "Cloudflare",
  "1password": "1Password",
  "lastpass": "LastPass",
  "nordvpn": "NordVPN",
  "expressvpn": "ExpressVPN",
  "malwarebytes": "Malwarebytes",
  "norton": "Norton",
  "mcafee": "McAfee",

  // -----------------------------------------------
  // TRAVEL & LODGING
  // -----------------------------------------------
  "airbnb": "Airbnb",
  "marriott": "Marriott",
  "hilton": "Hilton",
  "hyatt": "Hyatt",
  "ihg": "IHG",
  "intercontinental": "IHG",
  "wyndham": "Wyndham",
  "best western": "Best Western",
  "holiday inn": "Holiday Inn",
  "hampton inn": "Hampton Inn",
  "courtyard marriott": "Courtyard by Marriott",
  "residence inn": "Residence Inn",
  "sheraton": "Sheraton",
  "westin": "Westin",
  "w hotels": "W Hotels",
  "ritz carlton": "The Ritz-Carlton",
  "ritz-carlton": "The Ritz-Carlton",
  "four seasons": "Four Seasons",
  "fairmont": "Fairmont",
  "radisson": "Radisson",
  "la quinta": "La Quinta",
  "motel 6": "Motel 6",
  "super 8": "Super 8",
  "days inn": "Days Inn",
  "quality inn": "Quality Inn",
  "comfort inn": "Comfort Inn",
  "extended stay": "Extended Stay America",
  "delta airlines": "Delta Air Lines",
  "delta air": "Delta Air Lines",
  "american airlines": "American Airlines",
  "united airlines": "United Airlines",
  "southwest airlines": "Southwest Airlines",
  "jetblue": "JetBlue",
  "alaska airlines": "Alaska Airlines",
  "spirit airlines": "Spirit Airlines",
  "frontier airlines": "Frontier Airlines",
  "hawaiian airlines": "Hawaiian Airlines",
  "sun country": "Sun Country Airlines",
  "expedia": "Expedia",
  "booking.com": "Booking.com",
  "booking com": "Booking.com",
  "hotels.com": "Hotels.com",
  "hotels com": "Hotels.com",
  "priceline": "Priceline",
  "kayak": "Kayak",
  "tripadvisor": "TripAdvisor",
  "trip advisor": "TripAdvisor",
  "vrbo": "VRBO",
  "hertz": "Hertz",
  "enterprise rent": "Enterprise",
  "enterprise": "Enterprise",
  "avis": "Avis",
  "budget car rental": "Budget",
  "budget rent": "Budget",
  "national car": "National Car Rental",
  "alamo rent": "Alamo",
  "alamo": "Alamo",
  "thrifty car": "Thrifty",
  "dollar rent": "Dollar Car Rental",
  "sixt": "Sixt",
  "turo": "Turo",

  // -----------------------------------------------
  // UTILITIES & BILLS
  // -----------------------------------------------
  "comcast": "Comcast",
  "xfinity": "Xfinity",
  "spectrum": "Spectrum",
  "cox communications": "Cox",
  "cox cable": "Cox",
  "at&t": "AT&T",
  "att": "AT&T",
  "verizon": "Verizon",
  "t-mobile": "T-Mobile",
  "tmobile": "T-Mobile",
  "sprint": "Sprint",
  "boost mobile": "Boost Mobile",
  "metro by t-mobile": "Metro by T-Mobile",
  "cricket wireless": "Cricket Wireless",
  "straight talk": "Straight Talk",
  "mint mobile": "Mint Mobile",
  "visible wireless": "Visible",
  "google fi": "Google Fi",
  "optimum": "Optimum",
  "altice": "Altice",
  "frontier communications": "Frontier",
  "centurylink": "CenturyLink",
  "lumen": "Lumen",
  "windstream": "Windstream",
  "consolidated communications": "Consolidated Communications",
  "mediacom": "Mediacom",
  "wow internet": "WOW!",
  "wide open west": "WOW!",
  "astound broadband": "Astound Broadband",
  "rcn": "RCN",
  "sparklight": "Sparklight",
  "breezeline": "Breezeline",
  "eversource": "Eversource",
  "nationalgrid": "National Grid",
  "national grid": "National Grid",
  "con edison": "Con Edison",
  "coned": "Con Edison",
  "pge": "PG&E",
  "pg&e": "PG&E",
  "duke energy": "Duke Energy",
  "dominion energy": "Dominion Energy",
  "dte energy": "DTE Energy",
  "consumers energy": "Consumers Energy",
  "ameren": "Ameren",
  "entergy": "Entergy",
  "pseg": "PSEG",
  "comed": "ComEd",
  "nstar": "NStar",
  "pepco": "Pepco",
  "bge": "BGE",
  "southern company": "Southern Company",
  "georgia power": "Georgia Power",
  "florida power": "Florida Power & Light",
  "fpl": "Florida Power & Light",
  "tampa electric": "TECO",
  "we energies": "WE Energies",
  "xcel energy": "Xcel Energy",
  "evergy": "Evergy",
  "kcpl": "Evergy",
  "westar energy": "Evergy",

  // -----------------------------------------------
  // INSURANCE
  // -----------------------------------------------
  "geico": "GEICO",
  "geico auto": "GEICO",
  "progressive": "Progressive",
  "state farm": "State Farm",
  "allstate": "Allstate",
  "nationwide": "Nationwide",
  "farmers insurance": "Farmers Insurance",
  "usaa": "USAA",
  "liberty mutual": "Liberty Mutual",
  "travelers insurance": "Travelers",
  "hartford": "The Hartford",
  "the hartford": "The Hartford",
  "aig": "AIG",
  "metlife": "MetLife",
  "prudential": "Prudential",
  "new york life": "New York Life",
  "john hancock": "John Hancock",
  "northwestern mutual": "Northwestern Mutual",
  "cigna": "Cigna",
  "aetna": "Aetna",
  "humana": "Humana",
  "united healthcare": "UnitedHealthcare",
  "unitedhealthcare": "UnitedHealthcare",
  "anthem": "Anthem",
  "blue cross": "Blue Cross Blue Shield",
  "bluecross": "Blue Cross Blue Shield",
  "kaiser": "Kaiser Permanente",
  "molina": "Molina Healthcare",
  "centene": "Centene",

  // -----------------------------------------------
  // BANKING & FINANCE
  // -----------------------------------------------
  "venmo": "Venmo",
  "paypal": "PayPal",
  "zelle": "Zelle",
  "cash app": "Cash App",
  "cashapp": "Cash App",
  "square cash": "Cash App",
  "apple pay": "Apple Pay",
  "google pay": "Google Pay",
  "chime": "Chime",
  "robinhood": "Robinhood",
  "coinbase": "Coinbase",
  "kraken": "Kraken",
  "binance": "Binance",
  "sofi": "SoFi",
  "sofi bank": "SoFi",
  "ally bank": "Ally Bank",
  "ally financial": "Ally Bank",
  "marcus": "Marcus by Goldman Sachs",
  "marcus goldman": "Marcus by Goldman Sachs",
  "synchrony": "Synchrony",
  "affirm": "Affirm",
  "klarna": "Klarna",
  "afterpay": "Afterpay",
  "sezzle": "Sezzle",

  // -----------------------------------------------
  // PETS
  // -----------------------------------------------
  "petco": "Petco",
  "petsmart": "PetSmart",
  "pet supplies plus": "Pet Supplies Plus",
  "chewy": "Chewy",
  "pet supermarket": "Pet Supermarket",

  // -----------------------------------------------
  // EDUCATION
  // -----------------------------------------------
  "udemy": "Udemy",
  "coursera": "Coursera",
  "edx": "edX",
  "skillshare": "Skillshare",
  "linkedin learning": "LinkedIn Learning",
  "masterclass": "MasterClass",
  "duolingo": "Duolingo",
  "rosetta stone": "Rosetta Stone",
  "chegg": "Chegg",
  "bartleby": "Bartleby",
  "khan academy": "Khan Academy",
  "pluralsight": "Pluralsight",
  "treehouse": "Treehouse",
  "codecademy": "Codecademy",
  "datacamp": "DataCamp",

  // -----------------------------------------------
  // MISC / OTHER
  // -----------------------------------------------
  "payment thank you": "Payment",
  "payment - thank you": "Payment",
  "autopay payment": "Payment",
  "interest charged": "Interest Charge",
  "annual fee": "Annual Fee",
  "usps": "USPS",
  "ups store": "UPS Store",
  "ups": "UPS",
  "fedex": "FedEx",
  "dhl": "DHL",
  "the ups store": "UPS Store",
  "staples": "Staples",
  "office depot": "Office Depot",
  "officemax": "OfficeMax",
  "fedex office": "FedEx Office",
  "kinko's": "FedEx Office",
  "kinkos": "FedEx Office",
  "aaa": "AAA",
  "triple a": "AAA",
};