CREATE SCHEMA IF NOT EXISTS clio;
SET search_path TO clio;

DROP TABLE IF EXISTS
	transactions,
	chat_messages,
	chat_history,
	statement_summary,
	categories,
	merchants,
	statements,
	accounts,
	users
CASCADE;

DROP TYPE IF EXISTS statement_status;
DROP TYPE IF EXISTS speaker;

CREATE TABLE users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(64) UNIQUE NOT NULL,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL
);

CREATE TABLE accounts (
	account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	bank_name VARCHAR(64) NOT NULL, 
	account_number INT NOT NULL,
	account_type VARCHAR(64) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (user_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TYPE statement_status AS ENUM('queued', 'processing', 'complete', 'failed');

CREATE TABLE statements(
	statement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	account_id INT,
	period_start DATE,
	period_end DATE, 
	file_name VARCHAR(128) NOT NULL, 
	current_status statement_status NOT NULL DEFAULT 'queued',
	uploaded_at TIMESTAMPTZ,
	parsed_at TIMESTAMPTZ,
	error_message VARCHAR(128),
	CHECK (period_end >= period_start),
	FOREIGN KEY (user_id) REFERENCES users(user_id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (account_id) REFERENCES accounts(account_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE merchants(
	merchant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	merchant_name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE categories(
	category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL, 
	category_name VARCHAR(64) NOT NULL,
	UNIQUE (user_id, category_name),
	FOREIGN KEY (user_id) REFERENCES users (user_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE statement_summary(
	summary_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	statement_id INT NOT NULL UNIQUE,
	starting_balance NUMERIC(12,2),
	ending_balance NUMERIC(12,2),
	total_income NUMERIC(12,2),
	total_expenses NUMERIC(12,2),
	FOREIGN KEY (statement_id) REFERENCES statements(statement_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE chat_history(
	chat_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	user_id INT NOT NULL,
	title VARCHAR(64) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(), 
	FOREIGN KEY (user_id) REFERENCES users (user_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TYPE speaker AS ENUM ('user', 'llm');

CREATE TABLE chat_messages(
	messages_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	chat_id INT NOT NULL, 
	speaker_type speaker NOT NULL, 
	message_content VARCHAR(2048) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	FOREIGN KEY (chat_id) REFERENCES chat_history(chat_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE transactions (
	transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	user_id INT NOT NULL, 
	account_id INT NOT NULL, 
	statement_id INT, 
	merchant_id INT, 
	category_id INT, 
	category_confidence REAL NOT NULL DEFAULT 0, 
	transaction_date DATE NOT NULL, 
	description VARCHAR(128) NOT NULL,
	amount NUMERIC(12,2) NOT NULL,
	CHECK (category_confidence >= 0 AND category_confidence <= 1),
	FOREIGN KEY (user_id) REFERENCES users(user_id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (account_id) REFERENCES accounts(account_id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (statement_id) REFERENCES statements(statement_id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (merchant_id) REFERENCES merchants(merchant_id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (category_id) REFERENCES categories(category_id)
		ON UPDATE CASCADE ON DELETE SET NULL
);